-- MySQL Script generated by MySQL Workbench
-- Thu Nov 14 14:01:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tbla_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbla_documento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbla_documento` (
  `iddocumento` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(45) NULL,
  `direccion` VARCHAR(200) NULL,
  `telefono` VARCHAR(30) NULL,
  `correo` VARCHAR(300) NULL,
  `pasaporte` VARCHAR(200) NULL,
  PRIMARY KEY (`iddocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_Clientes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_Clientes` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `fecha de nacimiento` DATE NULL,
  `tbla_documento_iddocumento` INT NOT NULL,
  PRIMARY KEY (`idcliente`, `tbla_documento_iddocumento`),
  INDEX `fk_tbl_Clientes_tbla_documento1_idx` (`tbla_documento_iddocumento` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_Clientes_tbla_documento1`
    FOREIGN KEY (`tbla_documento_iddocumento`)
    REFERENCES `mydb`.`tbla_documento` (`iddocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbla_marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbla_marca` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbla_marca` (
  `idmarca` INT NOT NULL AUTO_INCREMENT,
  `nombre_marca` VARCHAR(100) NULL,
  `pais_origen` VARCHAR(50) NULL,
  `año_fundación` YEAR(20) NULL,
  `descripcion` VARCHAR(500) NULL,
  `fecha_resgistro` DATETIME NULL,
  `fecha_modificación` DATETIME NULL,
  `marca` VARCHAR(50) NULL,
  `modelo` VARCHAR(50) NULL,
  PRIMARY KEY (`idmarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbla_modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbla_modelo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbla_modelo` (
  `idmodelo` INT NOT NULL AUTO_INCREMENT,
  `nombre_modelo` VARCHAR(100) NULL,
  `año` YEAR(20) NULL,
  `tipo_vehiculo` VARCHAR(45) NULL,
  `fecha_resgistro` DATE NULL,
  `modelo` VARCHAR(50) NULL,
  `marca` VARCHAR(50) NULL,
  PRIMARY KEY (`idmodelo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_Vehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_Vehiculo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_Vehiculo` (
  `idVehiculo` INT NOT NULL AUTO_INCREMENT,
  `vin` VARCHAR(20) NULL,
  `numeroPlaca` VARCHAR(15) NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `año` INT NULL,
  `añoIngreso` DATE NULL,
  `tbla_marca_idmarca` INT NOT NULL,
  `tbla_modelo_idmodelo` INT NOT NULL,
  PRIMARY KEY (`idVehiculo`),
  INDEX `fk_tbl_Vehiculo_tbla_marca1_idx` (`tbla_marca_idmarca` ASC) VISIBLE,
  INDEX `fk_tbl_Vehiculo_tbla_modelo1_idx` (`tbla_modelo_idmodelo` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_Vehiculo_tbla_marca1`
    FOREIGN KEY (`tbla_marca_idmarca`)
    REFERENCES `mydb`.`tbla_marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_Vehiculo_tbla_modelo1`
    FOREIGN KEY (`tbla_modelo_idmodelo`)
    REFERENCES `mydb`.`tbla_modelo` (`idmodelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_oficina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_oficina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_oficina` (
  `idoficina` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `dirección` VARCHAR(100) NULL,
  `telefono` VARCHAR(15) NULL,
  `horarioapertura` DATE NULL,
  `horariocierre` DATE NULL,
  PRIMARY KEY (`idoficina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbla_estado_solicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbla_estado_solicitud` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbla_estado_solicitud` (
  `idestado_solicitud` INT NOT NULL AUTO_INCREMENT,
  `estado_solicitud` VARCHAR(200) NULL,
  `total` DECIMAL(10,2) NULL,
  `forma_pago` VARCHAR(200) NULL,
  `tipo_solicitud` VARCHAR(100) NULL,
  PRIMARY KEY (`idestado_solicitud`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbla_total`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbla_total` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbla_total` (
  `idtotal` INT NOT NULL AUTO_INCREMENT,
  `total` DECIMAL(10,2) NULL,
  `estado_solicitud` VARCHAR(100) NULL,
  `monto_descuento` DECIMAL(10,2) NULL,
  `monton_impuesto` DECIMAL(10,2) NULL,
  `fecha_actualizacion` DATETIME NULL,
  PRIMARY KEY (`idtotal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_Solicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_Solicitud` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_Solicitud` (
  `IdSolicitud` INT NOT NULL AUTO_INCREMENT,
  `Fechasolicitud` DATETIME NULL,
  `fechaentrega` DATETIME NULL,
  `fechahoradevolución` DATETIME NULL,
  `oficinaentrega` VARCHAR(45) NULL,
  `tbl_Vehiculo_idVehiculo` INT NOT NULL,
  `tbl_Clientes_idcliente` INT NOT NULL,
  `tbl_oficina_idoficina` INT NOT NULL,
  `tbla_estado_solicitud_idestado_solicitud` INT NOT NULL,
  `tbla_total_idtotal` INT NOT NULL,
  PRIMARY KEY (`IdSolicitud`),
  INDEX `fk_tbl_Solicitud_tbl_Vehiculo1_idx` (`tbl_Vehiculo_idVehiculo` ASC) VISIBLE,
  INDEX `fk_tbl_Solicitud_tbl_Clientes1_idx` (`tbl_Clientes_idcliente` ASC) VISIBLE,
  INDEX `fk_tbl_Solicitud_tbl_oficina1_idx` (`tbl_oficina_idoficina` ASC) VISIBLE,
  INDEX `fk_tbl_Solicitud_tbla_estado_solicitud1_idx` (`tbla_estado_solicitud_idestado_solicitud` ASC) VISIBLE,
  INDEX `fk_tbl_Solicitud_tbla_total1_idx` (`tbla_total_idtotal` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_Solicitud_tbl_Vehiculo1`
    FOREIGN KEY (`tbl_Vehiculo_idVehiculo`)
    REFERENCES `mydb`.`tbl_Vehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_Solicitud_tbl_Clientes1`
    FOREIGN KEY (`tbl_Clientes_idcliente`)
    REFERENCES `mydb`.`tbl_Clientes` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_Solicitud_tbl_oficina1`
    FOREIGN KEY (`tbl_oficina_idoficina`)
    REFERENCES `mydb`.`tbl_oficina` (`idoficina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_Solicitud_tbla_estado_solicitud1`
    FOREIGN KEY (`tbla_estado_solicitud_idestado_solicitud`)
    REFERENCES `mydb`.`tbla_estado_solicitud` (`idestado_solicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_Solicitud_tbla_total1`
    FOREIGN KEY (`tbla_total_idtotal`)
    REFERENCES `mydb`.`tbla_total` (`idtotal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_referencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_referencia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_referencia` (
  `idreferencia` INT NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(100) NULL,
  `fecha_de_nacimiento` DATE NULL,
  `tbl_Clientes_idcliente` INT NOT NULL,
  `tbla_documento_iddocumento` INT NOT NULL,
  PRIMARY KEY (`idreferencia`),
  INDEX `fk_tbl_referencia_tbl_Clientes1_idx` (`tbl_Clientes_idcliente` ASC) VISIBLE,
  INDEX `fk_tbl_referencia_tbla_documento1_idx` (`tbla_documento_iddocumento` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_referencia_tbl_Clientes1`
    FOREIGN KEY (`tbl_Clientes_idcliente`)
    REFERENCES `mydb`.`tbl_Clientes` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_referencia_tbla_documento1`
    FOREIGN KEY (`tbla_documento_iddocumento`)
    REFERENCES `mydb`.`tbla_documento` (`iddocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TBLA_segurobasico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TBLA_segurobasico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TBLA_segurobasico` (
  `idsegurobasico` INT NOT NULL AUTO_INCREMENT,
  `tipo_seguro` VARCHAR(50) NULL,
  `porcentaje_costo` DECIMAL(10,2) NULL,
  `costo_fijo` DECIMAL(10,2) NULL,
  `descripcion` VARCHAR(500) NULL,
  `seguro_basico` DECIMAL(10,2) NULL,
  `precio_por_dia` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idsegurobasico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tbl_precio_por_dia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tbl_precio_por_dia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tbl_precio_por_dia` (
  `id_precio_por_dia` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `moneda` VARCHAR(10) NULL,
  `estado` VARCHAR(15) NULL,
  `precio_por_dia` DECIMAL(10,2) NULL,
  `seguro_basico` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id_precio_por_dia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tbl_tarifa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tbl_tarifa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tbl_tarifa` (
  `idtarifa` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `monto` DECIMAL(10,2) NULL,
  `tbl_Vehiculo_idVehiculo` INT NOT NULL,
  `TBLA_segurobasico_idsegurobasico` INT NOT NULL,
  `Tbl_precio_por_dia_id_precio_por_dia` INT NOT NULL,
  PRIMARY KEY (`idtarifa`),
  INDEX `fk_Tbl_tarifa_tbl_Vehiculo1_idx` (`tbl_Vehiculo_idVehiculo` ASC) VISIBLE,
  INDEX `fk_Tbl_tarifa_TBLA_segurobasico1_idx` (`TBLA_segurobasico_idsegurobasico` ASC) VISIBLE,
  INDEX `fk_Tbl_tarifa_Tbl_precio_por_dia1_idx` (`Tbl_precio_por_dia_id_precio_por_dia` ASC) VISIBLE,
  CONSTRAINT `fk_Tbl_tarifa_tbl_Vehiculo1`
    FOREIGN KEY (`tbl_Vehiculo_idVehiculo`)
    REFERENCES `mydb`.`tbl_Vehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tbl_tarifa_TBLA_segurobasico1`
    FOREIGN KEY (`TBLA_segurobasico_idsegurobasico`)
    REFERENCES `mydb`.`TBLA_segurobasico` (`idsegurobasico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tbl_tarifa_Tbl_precio_por_dia1`
    FOREIGN KEY (`Tbl_precio_por_dia_id_precio_por_dia`)
    REFERENCES `mydb`.`Tbl_precio_por_dia` (`id_precio_por_dia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
